### ISSUE TITLE
Add support for new repository "JGI Genome Portal"

### ISSUE THREAD

**Issue by throwern** [bioenergy-research-centers/brc-schema#91]
Details in: https://github.com/bioenergy-research-centers/bioenergy.org/issues/138

There is a GLBRC dataset with this repository that is failing validation. Can we add "JGI Genome Portal" to the list of allowed repositories?

**Comment by ct-parker** [comment]
Copying details from linked bioenergy.org issue...

From the [GLBRC data feed](https://fair-data.glbrc.org/glbrc.json), Raw Data -> find 1390741

This is the full record (see line 8): `"repository": "JGI Genome Portal"`

```
{
      "title": "Bioenergy sorghum nodal root bud development: morphometric, transcriptomic and gene regulatory network analysis",
      "description": "Sorghum bicolor TX08001 Nodal Root Tissue Development Gene Expression Profiling",
      "date": "2024-11-10",
      "identifier": "1390741",
      "brc": "GLBRC",
      "bibliographicCitation": "https://genome.jgi.doe.gov/portal/SorbicEProfiling_60_FD/SorbicEProfiling_60_FD.info.html",
      "repository": "JGI Genome Portal",
      "analysisType": "RNA seq",
      "creator": [
        {
          "name": "John Mullet",
          "email": "john.mullet@ag.tamu.edu",
          "primaryContact": true,
          "affiliation": "GLBRC - Texas A&M"
        },
        {
          "name": "John Mullet",
          "email": "john.mullet@ag.tamu.edu",
          "primaryContact": false,
          "affiliation": "GLBRC - Texas A&M"
        }
      ],
      "relatedItem": [
        {
          "title": "Bioenergy sorghum nodal root bud development: morphometric, transcriptomic and gene regulatory network analysis",
          "relatedItemType": "JournalArticle",
          "relatedItemIdentifier": "https://www.frontiersin.org/journals/plant-science/articles/10.3389/fpls.2024.1456627/full"
        }
      ],
      "keywords": [
        "bioenergy sorghum, nodal root buds, development, transcriptome, gene regulatory network"
      ],
      "species": [
        {
          "scientificName": "Sorghum bicolor TX08001",
          "NCBITaxID": null
        }
      ]
    }
```

**Comment by caufieldjh** [comment]
Fixed in 5ff3f98

**Comment by ct-parker** [comment]
@caufieldjh Sorry to reopen, but could you bump the JSON schema version to 0.1.4 as well? It looks like the toml file is updated but #84 still isn't propagating to the JSON schema.

**Comment by caufieldjh** [comment]
Closing - this is up to date in 0.1.4
